
max_velocity = 1.0 # m/s
max_acceleration = 2.0 # m/s/s
start_velocity = 0.0 # m/s
end_velocity = 0.0 # m/s
is_reversed = false

[start_pose]
    x = 0.0
    y = 0.0
    angle = 0.0
[end_pose]
    x = 5.0
    y = 0.0
    angle = 0.0

[[internal_points]]
    x = 2.5
    y = 0.0